services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    build: requirements/mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - inception
    secrets:
      - sql_password
      - sql_root_password
  wordpress:
    container_name: wordpress
    image: wordpress:42
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - "9000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception
    secrets:
      - wp_admin_pass
      - wp_user_pass
      - sql_password
      - sql_root_password
  nginx:
    container_name: nginx
    image: nginx:42
    build: requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aborel/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aborel/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  wp_admin_pass:
    file: ./secrets/wp_admin_pass.txt
  sql_password:
    file: ./secrets/sql_password.txt
  sql_root_password:
    file: ./secrets/sql_root_password.txt
  wp_user_pass:
    file: ./secrets/wp_user_pass.txt
    