version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    build: requirements/mariadb
    volumes: 
      - mariadb: /var/lib/mysql


volumes:
  mariadb:
    name: mariadb
    