version: '5'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    build: requirements/mariadb
    volumes: 
      - mariadb: /var/lib/mysql
    expose:
      - 3306
    env_file:
      - .env
    restart: unless-stopped


volumes:
  mariadb:
    name: mariadb
    